export const PACKS = [
    {
        "id": "nhe",
        "level": "LV.1",
        "name": "NHẸ NHÀNG",
        "icon": "★",
        "accent": "#FFE600",
        "accentText": "#111",
        "btnBg": "#FFE600",
        "btnText": "#111",
        "desc": "Khởi động. Câu hỏi dễ thương, vui vẻ.",
        "tag": "SAFE",
        "truth": [
            "Kỷ niệm đáng xấu hổ nhất của bạn là gì?",
            "Bạn đã từng nói dối bạn bè chưa? Nói dối về điều gì?",
            "Crush đầu tiên của bạn trông như thế nào?",
            "Thói quen xấu nhất của bạn là gì?",
            "App bạn dùng nhiều nhất trên điện thoại là gì?",
            "Điều bí mật nào bạn chưa kể cho ai trong nhóm này?",
            "Bạn đã từng stalk ai trên mạng xã hội chưa?",
            "Bạn nghĩ ai trong nhóm này ăn nhiều nhất?",
            "Lần cuối bạn khóc là khi nào và vì sao?",
            "Bộ phim nào khiến bạn khóc nhiều nhất?",
            "Món ăn nào bạn ghét nhất mà mọi người đều thích?",
            "Bạn có bao giờ tự nói chuyện một mình trước gương không?",
            "Nickname hồi nhỏ của bạn là gì?",
            "Bạn đã từng giả vờ ốm để nghỉ học/nghỉ làm chưa?",
            "Ai là người bạn nhắn tin nhiều nhất trong 24h qua?",
            "Bạn có tin vào người ngoài hành tinh không?",
            "Nỗi sợ vô lý nhất của bạn là gì (ví dụ: sợ con gián, sợ bong bóng)?",
            "Bạn thích được tặng hoa hay tặng đồ ăn hơn?",
            "Nếu có 1 tỷ ngay bây giờ, món đồ đầu tiên bạn mua là gì?",
            "Bạn đã từng đi vệ sinh mà quên mang giấy chưa?",
            "Môn học nào hồi cấp 3 bạn sợ nhất?",
            "Bạn có bao giờ hát karaoke một mình trong phòng tắm không?",
            "Ai là người có gu thời trang ổn nhất trong nhóm này?",
            "Bạn thích mùa nào nhất trong năm?",
            "Tật xấu khi ngủ của bạn là gì (gác, nói mớ, ngáy)?",
            "Bạn có bao giờ lục lại ảnh cũ 5-10 năm trước rồi tự thấy 'ghê' không?",
            "Nếu được đổi tên, bạn muốn tên mình là gì?",
            "Bạn từng tiêu bao nhiêu tiền cho một món đồ 'vô tri' nhất?",
            "Trong phòng này, bạn thấy ai có vẻ ngoài 'hiền lành' nhất?",
            "Bạn đã bao giờ ngủ quên khi đang đi học/đi làm chưa?",
            "Món đồ đắt nhất bạn từng tự mua là gì?",
            "Lần gần nhất bạn nói dối cha mẹ là khi nào?",
            "Bạn có hay tự tìm tên mình trên Google không?",
            "Mùi gì bạn thấy thơm nhưng người khác lại thấy kinh (ví dụ: mùi xăng)?",
            "Bạn thích nhắn tin hay gọi điện hơn?",
            "Nếu được chọn một siêu năng lực vô dụng, bạn chọn gì?",
            "Bạn đã từng bị nhầm là người nổi tiếng hay ai khác chưa?",
            "Tin nhắn gần nhất bạn nhận được từ mẹ là gì?",
            "Bạn thích chó hay mèo hơn?",
            "Cuốn sách cuối cùng bạn đọc hết là cuốn nào?",
            "Bạn có bao giờ 'seen' tin nhắn mà không rep vì lười không?",
            "Nếu được xuyên không về quá khứ, bạn sẽ nhắn nhủ mình điều gì?",
            "Món ăn bạn có thể ăn cả tuần không chán là gì?",
            "Bạn đã từng bị ai đó block chưa?",
            "Trong nhóm này, ai là người có khả năng 'ế' lâu nhất?",
            "Bạn có thói quen xem bói hay xem tarot không?",
            "Câu nói cửa miệng của bạn là gì?",
            "Lần gần nhất bạn đi du lịch là khi nào?",
            "Bạn có bao giờ hát nhầm lời bài hát mà vẫn tự tin không?",
            "Nếu thế giới có zombie, ai trong nhóm sẽ là người hy sinh đầu tiên?",
            "Bạn có bao giờ tự đặt đồ ăn rồi giả vờ có người ăn cùng không?",
            "Bức ảnh gần nhất trong máy bạn là chụp cái gì?",
            "Bạn có hay nói chuyện với thú cưng như con người không?",
            "Nếu được sống ở một quốc gia khác, bạn chọn đâu?",
            "Màu sắc yêu thích của bạn là gì?",
            "Bạn đã từng bị bắt gặp đang nhảy một mình chưa?",
            "Ai là người bạn cảm thấy dễ nói chuyện nhất ở đây?",
            "Bạn thích ăn đồ ngọt hay đồ mặn hơn?",
            "Kỷ niệm đi học nào bạn nhớ nhất?",
            "Bạn có bao giờ làm rớt điện thoại vào mặt khi đang nằm không?",
            "Bạn có biết nấu món gì ngon nhất không?",
            "Lần đầu tiên bạn uống bia/rượu là khi nào?",
            "Bạn có hay xem livestream bán hàng không?",
            "Nếu được tham gia một show thực tế, bạn chọn show nào?",
            "Bạn có hay để ý đến số lượng like trên ảnh mình post không?",
            "Điều gì làm bạn cảm thấy tự tin nhất hôm nay?",
            "Bạn có hay quên chìa khóa hay điện thoại không?",
            "Kiểu tóc thảm họa nhất bạn từng để là gì?",
            "Bạn đã bao giờ mua đồ về nhưng chưa bao giờ dùng đến chưa?",
            "Món quà tệ nhất bạn từng nhận được là gì?",
            "Bạn có hay nói dối là 'Sắp đến rồi' khi vẫn đang ở nhà không?",
            "Ai là người có nụ cười đẹp nhất trong nhóm này?",
            "Bạn có hay sưu tầm món đồ gì không?",
            "Hồi nhỏ bạn ước mơ lớn lên làm gì?",
            "Bạn có hay để chuông báo thức rồi tắt đi ngủ tiếp không?",
            "Con vật nào bạn thấy giống tính cách của mình nhất?",
            "Bạn có bao giờ tự gửi tin nhắn cho mình để lưu thông tin không?",
            "Điều gì bạn thấy phiền nhất khi đi máy bay/tàu xe?",
            "Bạn có hay hát trong lúc làm việc không? Thường là gì ?",
            "Nếu chỉ được mang 1 món đồ lên hoang đảo, đó là gì?",
            "Bạn thích đi xem phim một mình hay đi với bạn?",
            "Thứ gì trong ví bạn luôn có ngoài tiền?",
            "Bạn đã bao giờ cười lúc không nên cười chưa?",
            "Bạn có hay tin vào cung hoàng đạo không?",
            "Ai là người nhắn tin 'nhây' nhất nhóm?",
            "Bạn có bao giờ giả vờ không thấy người quen trên đường không?",
            "Điều gì khiến bạn dễ mất kiên nhẫn nhất?",
            "Bạn thích làm việc buổi sáng hay ban đêm?",
            "Nếu có thể xóa một ứng dụng vĩnh viễn khỏi trái đất, đó là gì?",
            "Bạn đã từng đi xem phim mà ngủ quên trong rạp chưa?",
            "Lần cuối bạn tập thể dục là khi nào?",
            "Bạn có thói quen soi gương mỗi khi đi ngang qua cửa kính không?",
            "Nếu được tặng một chuyến du lịch miễn phí, bạn đi cùng ai?",
            "Món ăn đường phố nào bạn tâm đắc nhất?",
            "Bạn có bao giờ bị giáo viên gọi lên bảng mà không thuộc bài chưa?",
            "Số điện thoại bạn nhớ nhất (ngoài số của mình) là của ai?",
            "Bạn thích phong cách ăn mặc 'minimalism' hay rực rỡ?",
            "Điều gì khiến bạn thấy yêu đời nhất vào buổi sáng?",
            "Bạn có bao giờ bị nấc cụt mà không dừng lại được chưa?",
            "Nếu được làm sếp 1 ngày, bạn sẽ ra lệnh gì đầu tiên?"
        ],
        "dare": [
            "Làm 15 cái jumping jack ngay bây giờ",
            "Nói một điều tốt về tất cả mọi người trong nhóm",
            "Hát một đoạn bài hát yêu thích không cần nhạc",
            "Làm mặt xấu nhất có thể và chụp ảnh gửi nhóm chat",
            "Nói ra 3 điều bạn thích về người ngồi bên cạnh",
            "Đứng dậy nhảy một điệu bất kỳ trong 30 giây",
            "Gọi điện cho một người bạn và hát Happy Birthday",
            "Làm biểu cảm khuôn mặt từng người trong nhóm",
            "Đổi điện thoại cho người bên cạnh trong 1 phút",
            "Kể một câu chuyện cười trong 1 phút",
            "Thử liếm khuỷu tay của chính mình",
            "Giả tiếng một con vật bất kỳ để cả nhóm đoán",
            "Để người bên phải vẽ lên mặt bạn một hình nhỏ bằng bút",
            "Ăn một miếng chanh hoặc đồ chua mà không được nhăn mặt",
            "Nói chuyện bằng giọng miền Trung/Nam/Bắc trong 2 vòng tiếp theo",
            "Đứng bằng một chân trong vòng 2 phút",
            "Tự selfie một tấm góc chết và đặt làm hình nền điện thoại 5 phút",
            "Đọc to 3 tin nhắn gần nhất trong Messenger (trừ tin riêng tư)",
            "Làm hành động 'bắn tim' với một người lạ (nếu đang ở quán)",
            "Đổi vị trí ngồi với người xa bạn nhất hiện tại",
            "Vừa nhảy vừa đọc bảng chữ cái ngược",
            "Cho mọi người xem lịch sử tìm kiếm Youtube gần nhất",
            "Gửi icon '❤️' cho người thứ 5 trong danh sách online Facebook",
            "Uống một ngụm nước theo kiểu sang chảnh nhất có thể",
            "Diễn tả hành động đánh răng bằng một tay, tay kia cầm chân",
            "Làm hành động giống một meme nổi tiếng",
            "Cho người bên cạnh chỉnh lại tóc cho bạn",
            "Kể tên tất cả những người có mặt trong phòng kèm theo biệt danh tự chế",
            "Đứng lên tuyên bố 'Tôi là người đẹp nhất ở đây' thật dõng dạc",
            "Uống nước bằng cách dùng thìa/muỗng cho hết 1 ly",
            "Làm hành động 'aegyo' (dễ thương) trong vòng 30 giây",
            "Giả vờ đang catwalk từ đầu phòng đến cuối phòng",
            "Để người bên trái chọn 1 app bất kỳ và bạn phải xóa nó (chọn app rác thôi nhé)",
            "Vỗ tay 20 cái bằng một tay (đập vào đùi hoặc cánh tay khác)",
            "Làm động tác như đang bơi trên sàn nhà",
            "Đeo tất vào tay và dùng tay đó uống nước",
            "Kể lại một cốt truyện phim trong 30 giây theo phong cách kiếm hiệp",
            "Thực hiện 10 cái squat",
            "Giả làm người dẫn chương trình thời sự bản tin tối nay",
            "Nói một câu tiếng Anh/tiếng nước ngoài bất kỳ thật thần thái",
            "Để mọi người chụp ảnh bạn lúc đang 'đơ' nhất",
            "Làm mặt nũng nịu xin người bên cạnh cho 1 ngụm nước",
            "Thử giữ thăng bằng một đồ vật trên đầu trong 1 phút",
            "Nói 'Anh/Em yêu cả nhà' theo 3 tông giọng khác nhau",
            "Giả tiếng khóc của trẻ con",
            "Cố gắng không chớp mắt trong vòng 45 giây",
            "Quay 5 vòng tại chỗ rồi đi thẳng một đường",
            "Lấy điện thoại ra và thả tim cho 5 ảnh liên tiếp trên feed",
            "Hãy thử chạm mũi bằng lưỡi",
            "Gửi một sticker 'khùng điên' cho người thân nhất trên Zalo",
            "Làm hành động như đang chơi đàn guitar điện cực cháy",
            "Đứng lên và vẫy chào mọi người xung quanh như hoa hậu",
            "Đọc một bài thơ hoặc lời bài hát theo phong cách 'rap'",
            "Cho người đối diện mượn kính hoặc phụ kiện bạn đang đeo",
            "Tự khen mình 3 câu không được ngượng",
            "Hãy làm hành động như đang bắt một con ruồi tưởng tượng",
            "Giả vờ đang trang điểm cho người ngồi bên cạnh",
            "Kể tên 5 loại rau củ trong vòng 5 giây",
            "Làm động tác plank trong 30 giây",
            "Hãy nói một câu bí mật vào tai người bên cạnh",
            "Nhắm mắt và đoán xem ai đang chạm vào vai mình",
            "Thử uốn dẻo ngón tay theo một hình thù kỳ lạ",
            "Đóng giả một người bán hàng rong",
            "Hãy cười như một nhân vật phản diện trong phim",
            "Uống nước mà không được dùng tay chạm vào ly",
            "Để người bên phải đặt lại avatar Zalo cho bạn trong 2 phút",
            "Hát một câu hát có chứa tên một người trong nhóm",
            "Làm điệu bộ của người đang say rượu (dù đang tỉnh)",
            "Thực hiện động tác yoga đơn giản nhất",
            "Giả tiếng mèo kêu cho đến khi có người vuốt đầu bạn",
            "Kể về một món đồ bạn đang mặc trên người (mua ở đâu, giá nhiêu)",
            "Tự đấm bóp vai cho người bên trái trong 1 phút",
            "Làm hành động 'dab' 5 lần liên tục",
            "Vẽ một con mèo bằng tay không thuận",
            "Hãy thử không cười trong khi cả nhóm tìm cách chọc bạn",
            "Đứng lên và thực hiện động tác vươn vai như buổi sáng",
            "Làm hành động như đang chèo thuyền",
            "Nói 'Tôi đồng ý' với bất cứ điều gì người bên cạnh nói trong 1 phút",
            "Giả vờ đang cầm gương soi và tự luyến",
            "Hãy thử hắt hơi (giả vờ) thật to",
            "Đếm từ 1 đến 20 theo tông giọng trầm dần",
            "Nói về một sở thích kỳ lạ của mình một cách tự hào",
            "Hãy làm hành động như đang quay phim slow-motion",
            "Để người bên cạnh dùng điện thoại bạn chụp một tấm hình bất kỳ",
            "Làm động tác bắn cung vào một người trong phòng",
            "Hãy thử nói chuyện mà không cử động môi",
            "Đóng vai người hầu bàn phục vụ nước cho mọi người",
            "Cúi chào mọi người theo phong cách hoàng gia",
            "Hãy thử làm động tác robot",
            "Tự giới thiệu bản thân như một siêu anh hùng",
            "Làm hành động lau kính cho người đang đeo kính",
            "Hãy thử tưởng tượng bạn đang cầm một quả bóng bay và nó bị xì hơi",
            "Vỗ tay theo nhịp một bài hát thiếu nhi",
            "Hãy nói 'Mlem mlem' mỗi khi bạn ăn hoặc uống gì đó trong vòng 5 phút",
            "Làm hành động như đang câu cá",
            "Hãy thử tạo dáng chụp ảnh tạp chí",
            "Nói một câu chúc ngủ ngon thật ngọt ngào cho cả nhóm",
            "Làm hành động như đang đánh trống",
            "Hãy thử đi lại bằng gót chân trong vòng 30 giây",
            "Tặng một 'nụ hôn gió' cho người ngồi xa nhất"
        ]
    },
    {
        "id": "nhau",
        "level": "LV.2",
        "name": "NHẬU PHÊ",
        "icon": "●",
        "accent": "#FF3300",
        "accentText": "#fff",
        "btnBg": "#FF3300",
        "btnText": "#fff",
        "desc": "Câu hỏi sâu hơn.",
        "tag": "18+",
        "truth": [
            "Ai là người bạn ghét nhất công ty nhưng vẫn phải giả vờ quý?",
            "Lần say rượu tệ nhất trong đời bạn là gì?",
            "Bạn đã từng nhắn tin cho người yêu cũ khi say chưa?",
            "Điều bạn ân hận nhất sau một đêm nhậu là gì?",
            "Bạn đã từng ngủ quên ở đâu lạ nhất chưa?",
            "Ai trong nhóm mà bạn biết uống nhiều nhất nhưng giả vờ ít?",
            "Bạn đã từng trốn khỏi quán bar bỏ lại bạn bè chưa?",
            "Điều ngốc nghếch nhất bạn làm khi say là gì?",
            "Bạn đã chi nhiều tiền nhất cho một đêm nhậu là bao nhiêu?",
            "Bạn có thói quen gì kỳ lạ khi say không?",
            "Ai là người bạn thấy 'vô duyên' nhất trong đám bạn cũ?",
            "Bạn đã từng thích thầm anh/chị em của bạn thân chưa?",
            "Lần cuối cùng bạn 'thả thính' một người là khi nào?",
            "Bạn có bao giờ lục ví hoặc điện thoại của người yêu chưa?",
            "Mối tình ngắn nhất của bạn kéo dài bao lâu?",
            "Bạn đã từng bị ai đó block chưa? Vì sao?",
            "Bạn thích được khen về ngoại hình hay trí tuệ hơn?",
            "Nếu được 'tới bến' với một celeb, bạn sẽ chọn ai?",
            "Bạn đã từng đi làm trong tình trạng vẫn còn say chưa?",
            "Điều gì bạn thấy tự ti nhất về cơ thể mình?",
            "Bạn có bao giờ nói dối lương với bạn bè không?",
            "Ai trong bàn này là người bạn cảm thấy khó tin tưởng nhất?",
            "Bạn đã từng bị bắt gặp khi đang làm chuyện nhạy cảm chưa?",
            "Bạn có tin vào tình yêu sét đánh không, hay chỉ là do ngoại hình?",
            "Sai lầm lớn nhất của bạn trong một mối quan hệ là gì?",
            "Bạn đã từng chia tay ai đó qua tin nhắn chưa?",
            "Mối quan hệ mập mờ lâu nhất của bạn là bao nhiêu lâu?",
            "Bạn có bao giờ 'bắt cá hai tay' chưa?",
            "Điều gì ở người yêu cũ khiến bạn vẫn còn thấy ám ảnh?",
            "Lần cuối bạn stalk người yêu cũ là khi nào?",
            "Bạn đã từng hôn người cùng giới bao giờ chưa?",
            "Bạn có bao giờ giả vờ đạt cực khoái chưa?",
            "Bạn đã từng có ý định quay lại với người cũ chỉ vì cô đơn chưa?",
            "Ai là người trong phòng này có 'vibe' hợp để yêu nhất với bạn?",
            "Bạn đã bao giờ tiêu tiền vào những thứ không lành mạnh chưa?",
            "Điều gì bạn làm khi ở một mình mà không bao giờ muốn ai thấy?",
            "Bạn có bao giờ thấy ghen tị với thành công của bạn thân không?",
            "Bạn đã từng bị ai đó đá một cách thảm hại chưa?",
            "Món đồ đắt nhất bạn mua để 'sống ảo' là gì?",
            "Bạn có bao giờ dùng nick clone để đi 'khẩu nghiệp' chưa?",
            "Lần cuối bạn nói dối để đi chơi đêm là khi nào?",
            "Bạn đã từng bị cảnh sát giao thông dừng xe trong tình trạng có cồn chưa?",
            "Bạn có bao giờ cảm thấy hối hận vì đã kết bạn với ai đó ở đây không?",
            "Ai là người có ấn tượng đầu tiên tệ nhất với bạn trong nhóm này?",
            "Bạn đã bao giờ đi xem mắt chưa? Kết quả thế nào?",
            "Điều gì bạn thấy phiền nhất ở người yêu hiện tại (hoặc gần nhất)?",
            "Bạn có bao giờ thích người yêu của bạn mình không?",
            "Lần say nào khiến bạn 'mất sạch' hình tượng nhất?",
            "Bạn có từng có quỹ đen không?",
            "Bạn nghĩ gì về việc sống thử trước hôn nhân?",
            "Đã bao giờ bạn nhận nhầm tin nhắn của một người 'thả thính' mình chưa?",
            "Ai là người bạn muốn tránh mặt nhất vào lúc này?",
            "Bạn đã từng bị ai đó từ chối phũ phàng chưa?",
            "Điều gì khiến bạn dễ 'nổi máu' ghen tuông nhất?",
            "Bạn có bao giờ giả vờ say để được ai đó đưa về chưa?",
            "Mối quan hệ xa nhất bạn từng có là bao nhiêu km?",
            "Bạn đã bao giờ bị lừa tiền chưa? Kể lại xem nào.",
            "Bạn có bao giờ thấy mình quá tự cao không?",
            "Điều gì bạn thấy mình tệ nhất trong việc làm người yêu?",
            "Bạn có bao giờ 'ghost' (biến mất) ai đó không một lời giải thích chưa?",
            "Nếu phải chọn một người ở đây để đi du lịch riêng 1 tuần, bạn chọn ai?",
            "Bạn có hay xem phim 18+ không? Tần suất thế nào?",
            "Lần cuối bạn cảm thấy rung động thật sự là khi nào?",
            "Bạn có bao giờ đi bar/club một mình để tìm đối tượng chưa?",
            "Điều gì khiến bạn muốn kết thúc một mối quan hệ ngay lập tức?",
            "Bạn có bao giờ ước mình vẫn còn độc thân (nếu đã có chủ) không?",
            "Ai là người bạn thấy có cuộc sống đáng ngưỡng mộ nhất ở đây?",
            "Bạn có bao giờ so sánh người yêu hiện tại với người cũ không?",
            "Lần đầu tiên bạn biết 'chuyện ấy' là từ đâu?",
            "Bạn có bao giờ bị ai đó gạ gẫm một cách khiếm nhã chưa?",
            "Điều gì ở bản thân mà bạn muốn thay đổi nhất để thu hút người khác?",
            "Bạn đã từng bị người thân bắt gặp khi đang xem phim nhạy cảm chưa?",
            "Bạn có bao giờ gửi ảnh 'mát mẻ' cho ai đó chưa?",
            "Điều gì bạn thấy hối tiếc nhất trong thời thanh xuân?",
            "Bạn có bao giờ tiêu hết lương ngay trong tuần đầu tiên không?",
            "Ai là người bạn thấy 'nguy hiểm' nhất trong nhóm này?",
            "Bạn có bao giờ làm gì đó trái pháp luật (nhẹ) chưa?",
            "Lần cuối bạn cãi nhau to với bố mẹ là về vấn đề gì?",
            "Bạn đã bao giờ yêu đơn phương bạn thân chưa?",
            "Điều gì bạn thấy 'toxic' nhất ở chính mình?",
            "Bạn có bao giờ giả vờ nghèo để thử lòng ai đó chưa?",
            "Bạn nghĩ mình là người hướng nội hay hướng ngoại 'fake'?",
            "Lần gần nhất bạn cảm thấy cực kỳ cô đơn là khi nào?",
            "Bạn có bao giờ hối hận vì đã chọn ngành học/công việc hiện tại không?",
            "Ai là người bạn sẽ gọi đầu tiên nếu bị bắt vào đồn cảnh sát?",
            "Bạn có bao giờ giấu giếm giới tính thật của mình không?",
            "Điều điên rồ nhất bạn từng làm để gây chú ý với crush là gì?",
            "Bạn có bao giờ thấy mình là 'người thứ ba' trong một mối quan hệ chưa?",
            "Lần cuối bạn dùng app hẹn hò là khi nào?",
            "Bạn có bao giờ bị sếp mắng đến mức muốn nghỉ việc ngay lập tức chưa?",
            "Điều gì bạn chưa từng dám làm vì sợ người khác đánh giá?",
            "Bạn đã bao giờ làm hỏng đồ của người khác rồi im lặng chưa?",
            "Ai là người bạn thấy hay 'thả thính' dạo nhất ở đây?",
            "Bạn có bao giờ mơ thấy một người trong nhóm này chưa?",
            "Điều gì bạn thấy khó chịu nhất khi đi nhậu chung với nhóm?",
            "Bạn đã bao giờ yêu một người lớn hơn mình nhiều tuổi chưa?",
            "Bạn có bao giờ bị mất trí nhớ tạm thời sau một đêm say chưa?",
            "Điều gì bạn thấy mình may mắn nhất cho đến giờ?",
            "Bạn có bao giờ giả vờ bận để không phải đi họp lớp chưa?",
            "Nếu được thay đổi một quyết định trong quá khứ, bạn sẽ đổi gì?"
        ],
        "dare": [
            "Uống một ly và kể một bí mật mà chưa ai biết",
            "Gọi cho người yêu cũ và nói 'tôi nhớ anh/chị'",
            "Uống theo kiểu không dùng tay",
            "Post một tấm ảnh xấu nhất của bạn lên story",
            "Ngồi im không nói gì trong 3 phút, ai làm mình cười uống 2 ly",
            "Gọi điện cho bố/mẹ bằng giọng say",
            "Kể một chuyện tình cảm bí mật trong 2 phút",
            "Đổi ghế ngồi với người bạn ít thân nhất tối nay",
            "Tự phạt 2 ly nếu không dám làm một việc cả nhóm yêu cầu",
            "Uống mà không được nhìn xuống ly",
            "Cho người bên cạnh xem ảnh gần nhất trong 'Ảnh đã xóa gần đây'",
            "Nhắn tin cho sếp/đồng nghiệp: 'Em thấy anh/chị hôm nay rất lạ'",
            "Để một người trong nhóm dùng môi bạn làm 'giấy nháp' kẻ son",
            "Thực hiện một điệu nhảy sexy trên nền nhạc không lời",
            "Uống hết ly của người ngồi bên trái",
            "Thử thách 'nhìn nhau không cười' với người đối diện, ai cười uống 1 ly",
            "Cho mọi người xem danh sách 'Blacklist' trên Facebook của bạn",
            "Kể tên 3 người bạn từng ghét nhất và lý do (thật lòng)",
            "Gửi một tin nhắn 'Em/Anh đang làm gì đó?' cho crush cũ",
            "Để người bên phải kiểm tra thông báo Shopee/Lazada của bạn",
            "Uống một ly mix giữa 2 loại đồ uống có trên bàn",
            "Hát một bài hát thất tình thật thảm thiết",
            "Đọc to caption của 3 bài post gần nhất trên Instagram của bạn",
            "Thực hiện 10 lần squat trong khi vẫn cầm ly rượu",
            "Cho người bên cạnh mượn điện thoại lướt TikTok trong 2 phút",
            "Hãy uống một ly và kể về nụ hôn đầu tiên của bạn",
            "Cho mọi người xem 5 ảnh gần nhất trong Camera Roll",
            "Gọi điện cho một người bạn và giả vờ mình đang bị bắt cóc (trong 30s)",
            "Uống một ly bằng tai (đổ vào miệng nhưng áp ly vào tai - thách thức vui)",
            "Cho người bên cạnh gửi 1 tin nhắn bất kỳ cho bất cứ ai trong danh bạ",
            "Nhắm mắt lại và để mọi người cho bạn ăn một thứ gì đó trên bàn",
            "Hãy diễn tả lại cách bạn quyến rũ một người bằng ánh mắt",
            "Thực hiện 5 vòng xoay tại chỗ rồi thử rót rượu vào ly",
            "Đọc to phần 'Ghi chú' (Notes) gần nhất trong điện thoại",
            "Hãy để người bên trái vẽ một hình xăm giả lên tay bạn bằng bút bi",
            "Uống một ly và nói ra điểm yếu nhất của mình trong tình yêu",
            "Thực hiện một cú điện thoại troll: 'Alo, bên mình có bán thuốc trị hâm không?'",
            "Hãy để người đối diện kiểm tra lịch sử cuộc gọi của bạn",
            "Kể về một lần bạn bị 'quê' nhất trước mặt crush",
            "Uống một ly và thực hiện động tác hít đất 5 cái",
            "Hãy để nhóm chọn một bài hát và bạn phải nhảy theo phong cách hài hước",
            "Gửi một sticker 'cute' cho sếp của bạn (nếu dám)",
            "Hãy diễn lại biểu cảm của bạn khi bị người yêu đá",
            "Đứng lên và hô to 'Tôi yêu rượu bia' 3 lần",
            "Uống một ly mix giữa rượu và một món đồ ăn trên bàn",
            "Cho người bên cạnh xem tin nhắn gần nhất với mẹ/bố",
            "Hãy thử nói giọng lơ lớ như người nước ngoài trong 3 vòng",
            "Để mọi người đặt lại biệt danh Messenger của bạn trong 1 tuần",
            "Kể về một lần bạn làm chuyện 'bậy bạ' ở nơi công cộng",
            "Hãy uống một ly và đứng bằng một chân trong 1 phút",
            "Để người bên phải chọn 1 người trong nhóm để bạn nhắn tin 'I love you'",
            "Hãy diễn tả lại hành động của một người đang phê pha",
            "Uống một ly không dùng tay (nhờ người khác đổ)",
            "Hãy cho mọi người xem số dư tài khoản ngân hàng (hoặc app ví điện tử)",
            "Đọc to 5 tìm kiếm gần nhất trên Instagram/Facebook",
            "Hãy thử ngậm một ngụm nước và không được cười khi mọi người chọc",
            "Kể tên 3 người bạn muốn 'unfriend' nhất trên Facebook",
            "Uống một ly và thực hiện động tác catwalk vòng quanh bàn",
            "Hãy để người đối diện trang điểm cho bạn bằng bất cứ thứ gì có sẵn",
            "Gửi một lời mời kết bạn cho một người lạ trên Facebook",
            "Kể về một giấc mơ nhạy cảm bạn từng thấy về ai đó",
            "Hãy để người bên trái kiểm tra tin nhắn chờ (Spam) trên Facebook của bạn",
            "Uống một ly và nói một câu bằng tiếng Anh thật sành điệu",
            "Hãy thực hiện một hành động thân mật (ôm, cầm tay) với người bên cạnh trong 2 phút",
            "Đọc to một bình luận bạn từng viết trên mạng xã hội mà bạn thấy xấu hổ",
            "Hãy để cả nhóm chụp một tấm ảnh dìm hàng bạn và đăng lên story",
            "Uống hết một ly rượu của người ngồi xa bạn nhất",
            "Hãy kể về một lần bạn nói dối để đi chơi với người yêu",
            "Cho người bên cạnh xem danh sách chặn trên điện thoại",
            "Hãy thử giả giọng một người nổi tiếng nào đó",
            "Uống một ly và kể về sở thích 'kỳ quặc' nhất của bạn",
            "Hãy để người bên phải viết một status lên tường nhà bạn",
            "Thực hiện động tác 'múa quạt' trong vòng 30 giây",
            "Hãy gọi điện cho một cửa hàng đồ ăn và hỏi một câu ngớ ngẩn",
            "Uống một ly và kể về lần đầu tiên bạn say",
            "Hãy để mọi người xem những người bạn đã tìm kiếm trên Facebook gần đây",
            "Diễn tả một bộ phim chỉ bằng hành động để mọi người đoán",
            "Hãy thử ăn một miếng đồ ăn từ tay người bên trái",
            "Uống một ly và nói 'Tôi là kẻ tội đồ' thật sâu sắc",
            "Hãy để người bên cạnh gửi 1 icon 'thả thính' cho crush của bạn",
            "Kể về một lần bạn bị 'hớ' nặng nhất khi đi mua sắm",
            "Uống một ly và thực hiện động tác plank trong 30 giây",
            "Hãy để cả nhóm chọn một người để bạn phải khen ngợi trong 1 phút",
            "Gửi một tin nhắn 'Em nhớ anh/anh nhớ em' cho một người bạn thân khác giới",
            "Uống một ly và kể về một thói quen xấu khi đi tắm của bạn",
            "Hãy để người bên trái chọn một tấm ảnh trong máy bạn để gửi vào nhóm",
            "Thực hiện động tác 'bắn tim' với tất cả mọi người trong quán",
            "Hãy thử nói chuyện bằng tông giọng cao vút trong 2 vòng tiếp theo",
            "Uống một ly và kể về một lần bạn bị lừa tình",
            "Hãy để người đối diện quyết định hình phạt tiếp theo của bạn",
            "Tự tát nhẹ vào má mình và nói 'Tỉnh táo lại đi (Tên mình)'",
            "Hãy thử uống một ly rượu bằng ống hút",
            "Cho người bên cạnh xem lịch sử trình duyệt web (Tab ẩn danh thì thôi)",
            "Hãy kể tên một người bạn từng muốn 'vượt mức bạn bè' nhưng không thành",
            "Uống một ly và thực hiện một điệu nhảy Tiktok hot nhất hiện nay",
            "Hãy để người bên phải cầm điện thoại bạn trong vòng 5 phút",
            "Kể về một kỷ niệm đáng nhớ nhất với một người trong phòng này",
            "Uống một ly và nói thật cảm nhận của bạn về buổi nhậu hôm nay",
            "Hãy thử làm động tác cầu hôn người ngồi đối diện",
            "Kết thúc vòng này bằng cách uống hết ly của mình và hô 'Dzo!'"
        ]
    },
    {
        "id": "toiben",
        "level": "LV.3",
        "name": "TỚI BẾN",
        "icon": "▲",
        "accent": "#0033FF",
        "accentText": "#fff",
        "btnBg": "#0033FF",
        "btnText": "#fff",
        "desc": "Thách thức táo bạo hơn",
        "tag": "WILD",
        "truth": [
            "Điều bạn chưa bao giờ kể cho ai trong nhóm này nghe?",
            "Ai là người bạn thích nhất trong nhóm này — và tại sao?",
            "Nói ra một bí mật có thể làm ai đó giận bạn tối nay",
            "Khoảnh khắc bạn xấu hổ nhất trong đời là gì?",
            "Ai trong nhóm bạn nghĩ sẽ ly hôn sớm nhất?",
            "Điều bạn không bao giờ dám nói thẳng với sếp là gì?",
            "Bạn đã từng phản bội bạn thân chưa? Kể chi tiết",
            "Điều bạn nói dối nhiều nhất với người thân là gì?",
            "Nếu phải chọn một người trong nhóm này để tranh thủ 24h — bạn chọn ai?",
            "Kể một bí mật mà nếu người liên quan nghe được, mọi thứ sẽ thay đổi",
            "Bạn đã từng có tình một đêm chưa?",
            "Bạn nghĩ gì về 'Friends with Benefits'? Bạn đã thử chưa?",
            "Điều điên rồ nhất bạn từng làm trong phòng ngủ là gì?",
            "Bạn đã bao giờ dùng app hẹn hò để tìm 'đối tác' chưa?",
            "Ai là người bạn thấy hấp dẫn nhất về mặt giới tính trong phòng này?",
            "Lần cuối cùng bạn làm chuyện đó là khi nào?",
            "Bạn đã từng bị cắm sừng chưa, hay bạn là người đi cắm sừng?",
            "Bộ phận nào trên cơ thể người khác phái khiến bạn chú ý đầu tiên?",
            "Nếu được quay lại với một người yêu cũ, bạn chọn ai?",
            "Bạn có bao giờ nảy sinh tình cảm với đồng nghiệp chưa?",
            "Điều tồi tệ nhất bạn từng nói sau lưng một người đang ngồi ở đây?",
            "Bạn đã từng xem trộm tin nhắn của người yêu và phát hiện sự thật chưa?",
            "Nếu phải kết hôn với một người trong phòng để cứu thế giới, bạn chọn ai?",
            "Kể tên một người bạn từng muốn 'tác động vật lý' nhưng không thể",
            "Trải nghiệm 'giường chiếu' nào khiến bạn muốn quên đi nhất?",
            "Bạn đã bao giờ 'thử' với người cùng giới chưa? Nếu chưa, bạn có tò mò không?",
            "Tư thế yêu thích nhất của bạn là gì?",
            "Bạn đã bao giờ làm 'chuyện ấy' ở nơi công cộng (ngoài phòng ngủ) chưa?",
            "Bạn có bao giờ gửi clip nóng của mình cho ai chưa?",
            "Điều gì là 'turn-on' lớn nhất của bạn đối với một người?",
            "Bạn đã bao giờ giả vờ yêu một người chỉ vì tiền hoặc danh tiếng chưa?",
            "Nếu có thể ngủ với một người trong phòng này mà không có hậu quả, đó là ai?",
            "Bạn đã từng bị ai đó bắt gặp khi đang 'tự sướng' chưa?",
            "Khoản tiền lớn nhất bạn từng giấu người yêu/gia đình để chi cho việc không lành mạnh là bao nhiêu?",
            "Bạn có bao giờ nhắn tin sex (sexting) với một người lạ chưa?",
            "Điều gì là 'fetish' (sở thích đặc biệt) của bạn mà bạn thấy ngại nói ra?",
            "Bạn đã bao giờ yêu một người mà bạn biết chắc là họ đã có chủ chưa?",
            "Lần cuối cùng bạn khóc vì hối hận sau một cuộc tình là khi nào?",
            "Bạn đã bao giờ bí mật quay phim/chụp ảnh lúc đang làm chuyện đó chưa?",
            "Nếu phải tiết lộ mật khẩu ngân hàng cho 1 người ở đây, bạn chọn ai?",
            "Bạn đã bao giờ cảm thấy mình không còn yêu người yêu hiện tại nhưng chưa dám nói?",
            "Ai trong nhóm này là người bạn cảm thấy 'giả tạo' nhất?",
            "Bạn đã từng tham gia vào một cuộc tình tay ba chưa?",
            "Điều gì là bí mật đen tối nhất trong quá khứ của bạn?",
            "Bạn đã bao giờ dùng chất kích thích cấm chưa?",
            "Bạn có bao giờ nghĩ đến việc ngoại tình (hoặc đã làm) chưa?",
            "Điều gì khiến bạn thấy ghê tởm nhất ở người khác phái?",
            "Bạn đã từng đi quá giới hạn với ai đó rồi sau đó coi như không có chuyện gì xảy ra chưa?",
            "Bạn có bao giờ ghét bố mẹ mình không? Vì sao?",
            "Nếu phải chọn một người trong bàn để 'biến mất' vĩnh viễn, đó là ai?",
            "Bạn đã bao giờ hối hận vì đã sinh ra (hoặc có mặt trên đời) chưa?",
            "Điều gì bạn làm khiến bạn cảm thấy mình là một người tồi tệ?",
            "Bạn đã bao giờ lợi dụng tình cảm của ai đó để đạt được mục đích chưa?",
            "Bạn nghĩ gì về việc trao đổi đối tác (swinging)?",
            "Lần đầu tiên của bạn là năm bao nhiêu tuổi? Nó có tệ không?",
            "Bạn đã bao giờ bị trả thù tình chưa?",
            "Điều gì bạn thường xuyên tưởng tượng trong đầu nhưng không bao giờ dám thực hiện?",
            "Bạn có bao giờ lục lọi đồ cá nhân của bạn bè khi họ không có mặt không?",
            "Ai là người bạn cảm thấy cạnh tranh ngầm nhiều nhất trong công việc/cuộc sống?",
            "Bạn đã bao giờ nói dối về giới tính/xu hướng tính dục của mình chưa?",
            "Điều gì bạn thấy xấu hổ nhất về gia đình mình?",
            "Bạn đã từng có ý định phá hoại hạnh phúc của người khác chưa?",
            "Bạn có bao giờ giả vờ làm nạn nhân để nhận sự thương hại chưa?",
            "Lần cuối bạn làm điều gì đó trái đạo đức là khi nào?",
            "Bạn đã bao giờ nhìn lén người khác khi họ đang thay đồ/tắm chưa?",
            "Nếu được đổi mạng sống của mình lấy sự giàu có vô tận, bạn có làm không?",
            "Điều gì bạn thấy hèn nhát nhất ở chính mình?",
            "Bạn đã bao giờ bị tống tiền vì những hình ảnh/tin nhắn nhạy cảm chưa?",
            "Bạn nghĩ gì về việc 'bóc bánh trả tiền'?",
            "Ai là người bạn đã từng muốn 'ngủ cùng' nhất nhưng bị từ chối?",
            "Bạn đã bao giờ làm ai đó mang thai hoặc phải đi giải quyết hậu quả chưa?",
            "Điều gì bạn thấy tự mãn nhất về khả năng giường chiếu của mình?",
            "Bạn có bao giờ yêu một người vì họ giống người cũ không?",
            "Lần cuối bạn cảm thấy ghen tị đến mức muốn người khác gặp xui xẻo là khi nào?",
            "Bạn đã bao giờ bị đánh ghen chưa?",
            "Điều gì bạn đã thề sẽ mang xuống mồ không bao giờ kể?",
            "Bạn đã bao giờ lừa dối về học vấn hoặc bằng cấp của mình chưa?",
            "Bạn có bao giờ nghĩ mình sẽ là một người cha/mẹ tồi không?",
            "Điều gì bạn thấy ghét nhất ở người đang ngồi bên trái mình?",
            "Bạn đã bao giờ sử dụng dịch vụ nhạy cảm chưa?",
            "Nếu phải thừa nhận một tội lỗi lớn nhất tối nay, đó là gì?",
            "Bạn có bao giờ cảm thấy vui khi thấy người mình ghét thất bại không?",
            "Điều gì khiến bạn thấy mình là một kẻ thất bại nhất?",
            "Bạn đã bao giờ hứa hẹn một tương lai với ai đó dù biết mình sẽ bỏ họ chưa?",
            "Bạn đã bao giờ bị nghiện một thứ gì đó mà không thể dứt ra được chưa?",
            "Điều gì bạn đã làm khiến người thân của bạn phải thất vọng nhất?",
            "Bạn có bao giờ cảm thấy mình không có một người bạn thật sự nào không?",
            "Nếu ngày mai bạn chết, điều hối tiếc nhất bạn chưa làm là gì?",
            "Bạn đã bao giờ có tình cảm với một người đã có gia đình chưa?",
            "Điều gì bạn thấy mình giống 'phản diện' nhất?",
            "Bạn đã bao giờ trộm một món đồ gì đó quý giá chưa?",
            "Ai trong nhóm này là người bạn tin là đang giữ nhiều bí mật nhất?",
            "Bạn có bao giờ cảm thấy mình là một gánh nặng không?",
            "Điều gì bạn đã làm để leo lên vị trí hiện tại mà bạn không tự hào?",
            "Bạn đã bao giờ giả vờ bị bệnh tâm lý để được chú ý chưa?",
            "Nếu có thể xóa sổ một người khỏi ký ức của mình, đó là ai?",
            "Bạn đã bao giờ yêu một người chỉ vì ngoại hình của họ cực đẹp chưa?",
            "Điều gì bạn đã làm khi say mà bạn thấy không thể tha thứ cho mình?",
            "Bạn có bao giờ nghĩ đến việc bỏ trốn và bắt đầu một cuộc đời mới không?",
            "Câu hỏi cuối: Bạn có đang nói dối trong bất kỳ câu trả lời nào từ nãy đến giờ không?"
        ],
        "dare": [
            "Gửi một tin nhắn thật thà cho người bạn thầm thích",
            "Để mọi người trong nhóm post bất cứ ảnh gì lên story của bạn",
            "Gọi điện cho sếp và nói 'Mai tôi nghỉ'",
            "Để người bên cạnh đọc 10 tin nhắn gần nhất trong điện thoại",
            "Uống 3 ly liên tiếp không nghỉ",
            "Nói thật 3 điều bạn KHÔNG thích về người ngồi đối diện",
            "Để cả nhóm đặt nick name mới cho bạn trên điện thoại",
            "Nhắn tin cho người cuối cùng bạn nói chuyện: 'Anh/chị thích em không?'",
            "Kể chi tiết một cuộc cãi nhau tệ nhất bạn từng có",
            "Để cả nhóm đọc conversation dài nhất trên điện thoại",
            "Để người bên cạnh gửi một icon bất kỳ cho người yêu cũ của bạn",
            "Thực hiện một cú điện thoại troll người thân: 'Con sắp kết hôn'",
            "Cho phép một người trong nhóm thay đổi bio Facebook của bạn trong 24h",
            "Uống một ly và ngồi vào lòng người bên cạnh trong 1 vòng",
            "Cho mọi người xem ảnh 'nhạy cảm' nhất trong máy (nếu có) hoặc uống 3 ly",
            "Gỡ bỏ một món phụ kiện trên người (vòng, đồng hồ, kính...) cho đến hết game",
            "Để người bên trái viết một status và đăng lên tường nhà bạn",
            "Thì thầm một điều quyến rũ vào tai người ngồi đối diện",
            "Uống một ngụm rượu từ ly của người bạn thích nhất trong bàn",
            "Thực hiện động tác hít đất 20 cái, mỗi cái hô tên một người trong bàn",
            "Để cả nhóm kiểm tra lịch sử giao dịch ngân hàng tháng gần nhất",
            "Nhắn tin cho một người bạn cũ đã lâu không liên lạc: 'Tớ vẫn còn giữ món đồ đó'",
            "Ăn một món ăn do cả nhóm 'chế biến' từ các đồ có trên bàn",
            "Đóng vai một người phục vụ và đi xin số điện thoại ở bàn bên cạnh",
            "Hôn nhẹ vào má người ngồi bên phải bạn",
            "Hãy tháo tất của người bên trái bằng miệng",
            "Uống một shot và để một người trong nhóm dùng đá lạnh chà lên lưng bạn",
            "Để người đối diện kiểm tra tất cả các app hẹn hò trên máy bạn",
            "Hãy để người bên cạnh gửi 1 tin nhắn 'Em/Anh thèm...' cho một người ngẫu nhiên",
            "Ăn một miếng đồ ăn trên người của người ngồi đối diện (ví dụ trên tay)",
            "Hãy để cả nhóm chọn một bài hát và bạn phải nhảy thoát y (chỉ tháo 1 món đồ ngoài)",
            "Uống một ly và kể về lần bạn làm 'chuyện ấy' kỳ lạ nhất",
            "Hãy gọi điện cho người yêu cũ và nói 'Em/Anh vẫn còn giữ cái áo đó'",
            "Để một người trong nhóm 'hickey' vào cổ hoặc tay bạn",
            "Hãy để người bên cạnh đọc to 5 tin nhắn gần nhất trong Zalo",
            "Uống một shot và ngồi dưới gầm bàn cho đến vòng sau",
            "Thực hiện một cuộc gọi video cho một người bạn và không nói gì, chỉ nhìn chằm chằm",
            "Hãy để người bên phải kiểm tra hộp thư Instagram của bạn",
            "Uống 2 ly và mô tả tư thế yêu thích của bạn bằng hành động",
            "Hãy để cả nhóm viết bất cứ điều gì lên mặt bạn bằng bút không xóa được ngay",
            "Để một người trong nhóm lướt qua thư viện ảnh của bạn trong 30 giây",
            "Uống một shot và hôn vào tai người bên cạnh",
            "Hãy để người đối diện đặt một câu hỏi 'cực đoan' và bạn phải trả lời thật",
            "Nhắn tin cho mẹ: 'Con đang ở đồn cảnh sát, đừng gọi lại' (trong 1 phút rồi giải thích)",
            "Hãy để người bên cạnh đổi tên Facebook của bạn thành một cái tên ngớ ngẩn trong 24h",
            "Uống một ly và để mọi người xem danh sách video đã xem trên web ẩn danh (nếu có)",
            "Hãy thực hiện một điệu nhảy sexy với cái ghế bạn đang ngồi",
            "Để một người trong nhóm chọn một người lạ để bạn đi tới và 'nháy mắt'",
            "Uống một shot và nói ra tên người bạn từng 'ngủ cùng' mà thấy hối hận nhất",
            "Hãy để người bên trái cởi cúc áo trên cùng của bạn (nếu có)",
            "Nhắn tin cho crush: 'Em/Anh vừa mơ thấy chúng mình...' và không giải thích thêm",
            "Uống một ly và để một người trong nhóm dùng lưỡi chạm vào tai bạn",
            "Hãy để mọi người kiểm tra lịch sử tìm kiếm Google của bạn",
            "Uống 2 ly và mô tả một người trong nhóm mà bạn muốn 'vượt rào' cùng",
            "Hãy để người bên cạnh gửi 1 ảnh dìm hàng của bạn vào group gia đình",
            "Uống một shot và thực hiện động tác 'lap dance' với một người trong bàn",
            "Hãy để cả nhóm chọn một thử thách thể xác bất kỳ cho bạn",
            "Uống 3 ly liên tiếp và không được đi vệ sinh trong 30 phút tới",
            "Hãy để người đối diện dùng son môi viết chữ 'BAD' lên trán bạn",
            "Uống một ly và kể về một lần bạn bị bắt gặp khi đang 'tự sướng'",
            "Hãy để người bên trái cầm điện thoại bạn và đăng một tấm ảnh bất kỳ lên story",
            "Gửi tin nhắn cho sếp: 'Em có chuyện muốn nói riêng với anh/chị' rồi im lặng",
            "Uống một shot và để người bên cạnh đổ một chút nước đá vào trong áo",
            "Hãy thử hôn vào cổ người ngồi đối diện",
            "Để cả nhóm kiểm tra mục 'Gần đây' trong trình duyệt web của bạn",
            "Uống một ly và thừa nhận một điều bạn đã nói dối trong buổi tối này",
            "Hãy để người bên phải chọn một liên lạc trong máy để bạn gọi và nói 'Tôi yêu bạn'",
            "Thực hiện thử thách 'ngậm rượu trong miệng' trong khi mọi người chọc cười",
            "Uống 2 shot và để một người trong nhóm dùng dây buộc tay bạn lại trong 1 vòng",
            "Hãy để người bên trái kiểm tra tin nhắn Messenger với người yêu/crush",
            "Uống một ly và thực hiện hành động 'quỳ xuống' xin lỗi một người ở đây",
            "Hãy để cả nhóm chọn một bức ảnh trong máy bạn để đặt làm avatar Facebook",
            "Uống một shot và kể về lần bạn 'mất đời trai/gái'",
            "Hãy để người đối diện dùng bút vẽ một hình nhạy cảm lên cánh tay bạn",
            "Uống 3 ly và ngồi im lặng không được nói một từ nào cho đến khi đến lượt tiếp theo",
            "Hãy để người bên cạnh gửi một sticker nhạy cảm cho một người lớn tuổi trong danh bạ",
            "Uống một ly và nói thật lòng bạn thấy ai ở đây là 'kẻ phiền phức' nhất",
            "Hãy để mọi người xem các ứng dụng bạn đã cài đặt trên máy",
            "Uống 2 ly và thực hiện một động tác hít đất với người khác ngồi trên lưng",
            "Hãy để người bên trái viết một tin nhắn bất kỳ và gửi cho người bạn ghét nhất",
            "Uống một shot và để người đối diện cắn nhẹ vào vai bạn",
            "Hãy thử liếm một chút muối từ trên cổ tay của người ngồi bên cạnh",
            "Để cả nhóm kiểm tra danh sách 'Bạn bè thân thiết' trên Instagram của bạn",
            "Uống 3 ly và thừa nhận một bí mật mà bạn từng thề sẽ không kể với ai",
            "Hãy để người bên phải kiểm tra tin nhắn gần nhất của bạn trên Telegram/Viber",
            "Uống một ly và thực hiện một hành động 'mơn trớn' nhẹ nhàng với người bên cạnh",
            "Hãy để cả nhóm chọn một bài hát và bạn phải hát theo phong cách rên rỉ",
            "Uống một shot và để một người trong nhóm dùng khăn bịt mắt bạn lại trong 2 vòng",
            "Hãy để người đối diện chọn một người trong quán để bạn ra làm quen",
            "Uống 2 ly và nói ra số tiền hiện có trong ví của mình",
            "Hãy để người bên trái gửi một tin nhắn 'Em/Anh cần tiền' cho một người bạn",
            "Uống một shot và kể về một lần bạn bị từ chối phũ phàng nhất",
            "Hãy để cả nhóm chụp ảnh bạn đang làm hành động 'biến thái' nhất có thể",
            "Uống một ly và nói ra tên người bạn thấy 'ngon' nhất trong phòng này",
            "Hãy để người bên phải kiểm tra mục 'Ghi chú bảo mật' trong điện thoại bạn",
            "Uống 2 shot và để một người trong nhóm viết tên họ lên người bạn",
            "Hãy thử nói 'Tôi là nô lệ của bạn' với người ngồi đối diện",
            "Uống một ly và để mọi người xem lịch sử thanh toán Grab/Shopee Food",
            "Hãy để người bên trái quyết định xem bạn có được mặc tiếp áo/vòng/phụ kiện không",
            "Kết thúc bằng cách uống cạn ly và hôn vào tay tất cả mọi người trong bàn"
        ]
    },
    {
        id: "it_sinh_vien",
        level: "LV.IT",
        name: "DÂN IT",
        icon: "</> ",
        accent: "#00C44F",
        accentText: "#fff",
        btnBg: "#00C44F",
        btnText: "#fff",
        desc: "Dành riêng cho dân code. Deadline, bug, và những bí mật không bao giờ commit.",
        tag: "NERD",
        truth: [
            // ── CÁ NHÂN / HỌC TẬP ──
            "GPA thật của bạn là bao nhiêu? Không làm tròn lên.",
            "Bạn đã từng copy code trên StackOverflow mà không đọc hiểu rồi nộp bài chưa?",
            "Môn học nào bạn đã học vẹt nhất mà vẫn qua được?",
            "Bạn đã từng dùng ChatGPT làm bài tập lấy điểm chưa? Mức độ thế nào?",
            "Lần cuối bạn thức khuya code là mấy giờ? Kết quả có ra không?",
            "Bạn có thực sự hiểu thuật toán bạn vừa nộp bài không?",
            "Đồ án nhóm nào bạn không làm gì mà vẫn có tên không?",
            "Bạn đã từng GitHub clone repo người khác, đổi tên, rồi nộp chưa?",
            "Tech stack của bạn thật ra là gì? Học bao nhiêu phần thật, bao nhiêu phần hàng fake?",
            "Bạn đã từng bỏ buổi lab vì không làm bài tập chưa?",
            "Bạn đã bao giờ tắt máy ảo để thoát khỏi câu hỏi khó của thầy cô chưa?",
            "Framework bạn hay khoe biết nhưng thực ra chỉ làm được 'Hello World' là gì?",
            "Lần gần nhất bạn đọc documentation thật sự (không phải ctrl+F) là khi nào?",
            "Bạn đã từng hỏi ChatGPT debug lỗi mà sau đó vẫn không hiểu tại sao nó sai chưa?",
            "Dự án cá nhân bạn đã 'đang làm' lâu nhất mà vẫn chưa xong là gì? Bao nhiêu lâu rồi?",
            "Bạn đã từng nhận lời làm freelance rồi thuê người khác làm thay chưa?",
            "Nếu phải nói thật lúc phỏng vấn, skill nào bạn đang ghi trên CV nhưng chưa thực sự biết?",
            "Lần đầu tiên bạn dùng Linux là khi nào? Thoát vim chưa?",
            "Bạn đã bao giờ push thẳng lên main/master mà không review không?",
            "Commit message tệ nhất của bạn là gì? ('fix', 'update', 'asdfgh' không tính)",
            "Bạn đã từng xóa database production chưa? Kể đi.",
            "Số lần bạn restart lại máy để fix bug mà không biết bug ở đâu là bao nhiêu?",
            "Bạn có bao giờ viết comment 'TODO: fix later' rồi không bao giờ fix không?",
            "Lần cuối bạn viết unit test là khi nào? (Không tính test tự sinh từ AI)",
            // ── QUAN HỆ / XÃ HỘI ──
            "Bạn có crush trong lớp/nhóm không? Ai?",
            "Ai là người bạn hay nhờ debug nhất và sau đó 'cảm ơn' thế nào?",
            "Bạn có hay coi thường dân 'non-tech' không? Trả lời thật.",
            "Lần gần nhất bạn flex skill coding để gây ấn tượng với ai đó là khi nào?",
            "Bạn đã từng giả vờ biết một công nghệ để không bị coi thường chưa?",
            "Ai là người code giỏi nhất nhóm và bạn có thật sự thấy ghen tị không?",
            "Bạn hay thầm đánh giá code của người khác lúc pair programming không?",
            "Meme IT nào bạn hay share nhưng thật ra không hiểu hết ý nghĩa?",
            "Bạn có hay tắt camera trong buổi học online để làm việc riêng không?",
            "Bạn đã từng tham gia hackathon chỉ để lấy certificate rồi về chưa?",
            // ── NGHỀ NGHIỆP / TƯƠNG LAI ──
            "Bạn thật sự có muốn làm IT lâu dài không hay chỉ vì lương cao?",
            "Lương mong đợi khi ra trường của bạn là bao nhiêu? Nói thật, không cộng thêm 20%.",
            "Bạn đã apply bao nhiêu công ty intern rồi? Đậu bao nhiêu cái?",
            "Công ty nào bạn bị reject mà vẫn không muốn thừa nhận?",
            "Bạn có bao giờ nói 'làm startup cho vui' trong khi thật ra chỉ muốn vào Big Tech không?",
            "Nếu ngành IT không có mức lương cao, bạn có còn học không?",
            "Bạn có đang học thật hay chỉ build portfolio cho đẹp hồ sơ?",
            "Roadmap học lập trình của bạn đang ở bước mấy? Có theo đúng plan không?",
            "Bạn đã từng nói 'em đang nghiên cứu AI' trong khi chỉ đang xem YouTube không?",
            "Nếu phải chọn lại, bạn có chọn ngành IT không?",
            // ── CÔNG NGHỆ / ĐỜI SỐNG ──
            "Máy tính bạn đang dùng RAM bao nhiêu? Có đủ không?",
            "Bạn đã từng dùng Windows crack bao giờ chưa?",
            "Số tab Chrome đang mở lúc này là bao nhiêu?",
            "Bạn có dùng dark mode tất cả mọi thứ không? Kể cả những app không hỗ trợ?",
            "IDE bạn đang dùng là gì? Có justify được không hay chỉ vì 'anh senior bảo dùng'?",
            "Lần cuối bạn tắt máy đúng cách (không sleep/hibernate) là khi nào?",
            "Bạn có bao giờ đặt tên file quan trọng là 'final_final_v2_thật sự_xong.docx' không?",
            "Bạn dùng bao nhiêu màn hình? Có thật sự cần không hay chỉ cho oai?",
            "Folder Desktop của bạn hiện tại trông như thế nào?",
            "Keyboard của bạn là gì? Bạn có justify được cái giá đó không?",
            // ── THÊM MỚI ──
            "Bạn đã từng ngủ gật trong giờ học rồi bị gọi tên chưa?",
            "Bug kỳ lạ nhất bạn từng gặp mà sau đó tìm ra nguyên nhân ngớ ngẩn là gì?",
            "Bạn đã từng đổ lỗi cho môi trường/server khi thật ra là code bạn sai không?",
            "Lần đầu tiên bạn hiểu được một khái niệm khó (recursion, pointer, async...) là khi nào?",
            "Bạn đã bao giờ merge conflict rồi xóa sạch code của người khác chưa?",

            "Bạn đã từng build cả một feature rồi bị PM bảo 'thật ra không cần' chưa?",
            "Lần cuối bạn làm việc có hiệu quả thật sự (không distraction) là khi nào?",
            "Bạn có bao giờ đọc security warning mà vẫn click 'I understand the risk' không?",
            "Nếu mọi người có thể xem lịch sử code của bạn, điều bạn xấu hổ nhất là gì?",

            "Bạn đã từng viết code mà sau 1 tuần bạn chính mình không hiểu mình viết gì chưa?",
            "Ai trong nhóm này bạn nghĩ có tương lai trong ngành nhất?",
            "Ai trong nhóm này bạn nghĩ sẽ bỏ ngành IT sớm nhất?",
            "Bạn có bao giờ lên LinkedIn flex dự án mà thật ra bạn chỉ fix một cái bug nhỏ không?",
            "Bạn đã bao giờ tham gia một buổi code review mà không đọc code trước không?",
            "Nếu có thể gửi email ẩn danh cho giảng viên khó nhất, bạn sẽ viết gì?",
            "Bạn có bao giờ tự hỏi tại sao mình chọn IT trong lúc debug lúc 2 giờ sáng không?",
            "Ngôn ngữ lập trình nào bạn thật sự ghét nhưng vẫn phải học?",
            "Điều gì bạn ước mình được học sớm hơn trong ngành IT?",
            "Bạn có đang đi đúng hướng so với định hướng career ban đầu của mình không?",
            "Bạn sẽ nói gì với bản thân lúc mới vào học IT nếu có thể?",
            "Cái gì là điều bạn thấy được dạy ở trường nhưng chắc chắn không bao giờ dùng đến?",
            "Senior nào trong ngành bạn thần tượng và tại sao bạn chưa học theo họ?",
            "Bạn đã bao giờ cảm thấy mình là 'imposter' trong nhóm IT chưa?",
            "Bạn muốn làm gì nhất ngoài ngành IT nếu lập trình không tồn tại?",
        ],
        dare: [
            // ── CODING CHALLENGES ──
            "Mở IDE lên và viết FizzBuzz không dùng AI trong 3 phút. Nếu không xong: uống 2 ly.",
            "Giải thích recursion cho một người không biết IT trong nhóm trong 1 phút.",
            // ── ĐIỆN THOẠI / MÁY TÍNH ──
            "Cho cả nhóm xem Desktop màn hình chính máy tính bạn (share màn hình hoặc show thật).",
            "Mở tab cuối cùng trong Chrome bạn đang để mở và giải thích tại sao nó vẫn còn đó.",
            "Cho cả nhóm xem folder Downloads — không được xóa gì trước.",
            "Đọc to tên 5 file có tên kỳ lạ nhất trong máy tính.",
            "Mở phần mềm hoặc app trên máy mà bạn cài nhưng chưa bao giờ dùng.",
            "Cho cả nhóm xem số tab đang mở trên trình duyệt hiện tại.",
            "Chia sẻ màn hình điện thoại và để người bên cạnh lướt 30 giây.",
            "Mở VS Code (hoặc IDE) và cho mọi người xem project đang làm dở.",
            "Cho cả nhóm xem phần 'Recently Deleted' trong thư mục trash của máy.",
            "Đọc to 3 commit message tệ nhất trong lịch sử git của một project bất kỳ.",
            // ── XÃ HỘI / THÁCH THỨC ──
            "Nhắn tin cho một người ngoài nhóm: 'Anh/chị có biết sự khác nhau giữa TCP và UDP không?'",
            "Post một đoạn code lên story với caption 'Cái này easy lắm 😌' (code phải là của bạn).",
            "Gọi điện cho một người thân và giải thích blockchain trong 1 phút.",
            "Nhắn tin cho thầy/cô: 'Thầy/cô ơi em mới tìm ra cách tối ưu thuật toán thầy dạy hôm qua'",
            "Post lên LinkedIn một 'achievement' nhỏ nhặt nhất bạn có thể nghĩ ra (ví dụ: Tôi vừa thoát được vim lần đầu tiên).",
            "Viết review thật lòng về ngành IT trên một group Facebook bất kỳ.",
            "Nhắn tin cho người bạn hay nhờ debug: 'Cảm ơn mày, mày quan trọng với tao lắm'.",
            "Tạo một commit với message đúng chuẩn, rõ ràng và push lên GitHub ngay bây giờ.",
            "Rate bản thân từ 1–10 về skill coding và explain tại sao — thật lòng.",
            "Nhắn tin cho nhóm đồ án bất kỳ: 'Tao xin lỗi vì lần trước tao trễ deadline'.",
            // ── ROLEPLAY / DIỄN XUẤT ──
            "Giả vờ là Linus Torvalds đang trả lời bình luận trên mailing list trong 1 phút.",

            "Giả vờ bạn đang live stream coding — giải thích từng thao tác bạn đang làm trong 2 phút.",
            "Thuyết phục cả nhóm rằng PHP là ngôn ngữ tốt nhất thế giới — một cách nghiêm túc.",
            "Giả làm recruiter phỏng vấn người bên cạnh vào vị trí junior developer.",
            "Đóng vai một con bug đang giải thích lý do tại sao bạn tồn tại.",
            "Giả vờ bạn là 10x developer đang explain một cái gì đó 'self-evident'.",
            "Đọc Error log theo giọng kể chuyện cổ tích cho trẻ em nghe.",
            "Giả làm PM và báo với nhóm: 'Client muốn thêm feature nhưng không thêm deadline'.",
            "Trình bày một bản tech presentation về đề tài 'Tại sao mì gói là best practice của sinh viên IT'.",
            // ── THẬT SỰ THÁCH THỨC ──
            "Đổi background ảnh đại diện GitHub thành ảnh tự sướng xấu nhất trong 24h.",
            "Viết một hàm tên là 'fix_everything()' push lên GitHub public repo.",
            "Tạo một repo GitHub public tên 'my_terrible_code' và push một đoạn code xấu nhất bạn từng viết.",
            "Update LinkedIn thêm skill 'Microsoft Word' và 'Powerpoint' mức Expert.",
            "Nhắn tin vào group lớp: 'Ai có tài liệu môn [môn khó nhất] không? Em quên học rồi'.",
            "Đặt lại ảnh đại diện Zalo thành ảnh terminal với dòng chữ 'I use Arch btw'.",
            "Tạo một issue trên GitHub của một dự án nổi tiếng với tiêu đề thật sự nghiêm túc.",
            "Để người bên cạnh thay đổi theme IDE của bạn và bạn phải code với nó cả buổi.",
            "Uống 2 ly và live code một cái gì đó bất kỳ trong 5 phút, không hỏi yêu cầu.",
            "Kể tên tất cả ngôn ngữ lập trình bạn biết trong 30 giây — trung thực.",
            // ── UI/UX / FUN ──
            "Thiết kế UI cho app 'Đặt cơm trưa cho sinh viên IT lười nấu' bằng giấy trong 3 phút.",
            "Viết pseudo-code cho thuật toán 'làm thế nào để xin tiền bố mẹ khi hết tháng'.",
            "Mô tả project portfolio của bạn như bạn đang pitching cho nhà đầu tư.",
            "Nếu cuộc đời bạn là một codebase, bạn sẽ refactor gì đầu tiên?",
            "Giải thích tại sao bạn chọn ngành IT bằng một metaphor lập trình.",
            "Đặt tên biến mô tả từng người trong nhóm — không được dùng 'user1', 'user2'.",
            "Viết một regex pattern mô tả kiểu người bạn muốn yêu.",
            "Giải thích git rebase vs git merge bằng một drama tình cảm.",
            "Code review 'cuộc đời' của người ngồi đối diện — highlight bug và suggest improvement.",
            // ── HỌC TẬP ──

            "Giải thích tại sao bạn chưa làm xong side project bằng technical jargon.",
            "Kể tên tất cả các Design Pattern bạn biết — thật sự biết, không chỉ tên.",
            "Giải thích sự khác nhau giữa Stack và Queue bằng cách dùng đồ vật trên bàn.",
            "Chứng minh rằng bạn hiểu Big O notation bằng ví dụ thực tế trong cuộc sống.",
            "Mở một Leetcode problem bất kỳ (Easy) và giải thích approach — không cần code.",
            "Giải thích HTTP status codes bằng cảm xúc của bạn trong một ngày: 200, 404, 500, 418.",
            "Mô tả ngày hôm nay của bạn bằng git commands.",
            "Nếu bạn là một database, bạn đang ở dạng chuẩn hóa (normal form) thứ mấy?",
            "Giải thích CI/CD pipeline cho một người bán bánh mì.",
            // ── CUỐI GAME ──
            "Tạo một Kahoot về IT và bắt cả nhóm chơi ngay bây giờ.",
            "Đặt alarm 6 giờ sáng mai với tên 'Dậy code đi' và show cả nhóm.",
            "Tạo một group chat mới tên 'Deadline fighters' và thêm tất cả mọi người trong bàn.",
  
            "Commit code chưa xong với message 'WIP: life is too short' và push lên.",
            "Mở một PR (Pull Request) vào một repo bạn đang làm, dù nó chưa xong.",
            "Ghi 'lập trình viên trong tương lai' vào bio Instagram/Facebook trong 24h.",
            "Uống cạn ly và nói một câu gì đó truyền cảm hứng cho cả nhóm về IT — thật lòng, không sáo rỗng.",
        ],
    },
]

export const TICKER = [
    "UỐNG ĐI",
    "THẬT HAY THÁCH",
    "KHÔNG CÓ ĐƯỜNG LÙI",
    "AI DÁM?",
    "TỚI BẾN",
    "PHẠT UỐNG",
    "GAME ON",
    "KHÔNG SAY KHÔNG VỀ",
    "THOÁT XÁC",
    "BẮT ĐẦU CHÁY",
    "CHƠI LÀ CHỊU",
    "ĐỪNG NHÁT",
    "SAY QUÊN LỐI VỀ",
    "BÍ MẬT BỊ BẬT MÍ",
    "RƯỢU VÀO LỜI RA",
    "KHÔNG ĐƯỢC RÉ",
    "NHẬU THÔI",
    "HẾT MÌNH ĐÊ",
    "CHỐT ĐƠN",
    "SỐNG THẬT ĐI",
    "ĐỨNG HẾT DẬY",
    "CÒN THỞ CÒN GỠ",
    "ĐÃ CHƠI LÀ PHẢI CHÁY",
    "TRẢ LỜI ĐI",
];

export const PLAYER_COLORS = [
    "#FF3300",
    "#0033FF",
    "#FFE600",
    "#00C44F",
    "#FF69B4",
    "#FF8C00",
    "#9B59B6",
    "#1ABC9C",
];
