export const PACKS = [
    {
        id: "nhe",
        level: "LV.1",
        name: "NHẸ NHÀNG",
        icon: "★",
        accent: "#FFE600",
        accentText: "#111",
        btnBg: "#FFE600",
        btnText: "#111",
        desc: "Khởi động buổi tối. Câu hỏi dễ thương, thách thức vui vẻ.",
        tag: "SAFE",
        truth: [
            "Kỷ niệm đáng xấu hổ nhất của bạn là gì?",
            "Bạn đã từng nói dối bạn bè chưa? Nói dối về điều gì?",
            "Crush đầu tiên của bạn trông như thế nào?",
            "Thói quen xấu nhất của bạn là gì?",
            "App bạn dùng nhiều nhất trên điện thoại là gì?",
            "Điều bí mật nào bạn chưa kể cho ai trong nhóm này?",
            "Bạn đã từng stalk ai trên mạng xã hội chưa?",
            "Bạn nghĩ ai trong nhóm này ăn nhiều nhất?",
            "Lần cuối bạn khóc là khi nào và vì sao?",
            "Bộ phim nào khiến bạn khóc nhiều nhất?",
        ],
        dare: [
            "Làm 15 cái jumping jack ngay bây giờ",
            "Nói một điều tốt về tất cả mọi người trong nhóm",
            "Hát một đoạn bài hát yêu thích không cần nhạc",
            "Làm mặt xấu nhất có thể và chụp ảnh gửi nhóm chat",
            "Nói ra 3 điều bạn thích về người ngồi bên cạnh",
            "Đứng dậy nhảy một điệu bất kỳ trong 30 giây",
            "Gọi điện cho một người bạn và hát Happy Birthday",
            "Làm biểu cảm khuôn mặt từng người trong nhóm",
            "Đổi điện thoại cho người bên cạnh trong 1 phút",
            "Kể một câu chuyện cười trong 1 phút",
        ],
    },
    {
        id: "nhau",
        level: "LV.2",
        name: "NHẬU PHÊ",
        icon: "●",
        accent: "#FF3300",
        accentText: "#fff",
        btnBg: "#FF3300",
        btnText: "#fff",
        desc: "Bắt đầu nóng. Câu hỏi sâu hơn, thách thức táo bạo hơn.",
        tag: "18+",
        truth: [
            "Ai là người bạn ghét nhất công ty nhưng vẫn phải giả vờ quý?",
            "Lần say rượu tệ nhất trong đời bạn là gì?",
            "Bạn đã từng nhắn tin cho người yêu cũ khi say chưa?",
            "Điều bạn ân hận nhất sau một đêm nhậu là gì?",
            "Bạn đã từng ngủ quên ở đâu lạ nhất chưa?",
            "Ai trong nhóm mà bạn biết uống nhiều nhất nhưng giả vờ ít?",
            "Bạn đã từng trốn khỏi quán bar bỏ lại bạn bè chưa?",
            "Điều ngốc nghếch nhất bạn làm khi say là gì?",
            "Bạn đã chi nhiều tiền nhất cho một đêm nhậu là bao nhiêu?",
            "Bạn có thói quen gì kỳ lạ khi say không?",
        ],
        dare: [
            "Uống một ly và kể một bí mật mà chưa ai biết",
            "Gọi cho người yêu cũ và nói 'tôi nhớ anh/chị'",
            "Uống theo kiểu không dùng tay",
            "Post một tấm ảnh xấu nhất của bạn lên story",
            "Ngồi im không nói gì trong 3 phút, ai làm mình cười uống 2 ly",
            "Gọi điện cho bố/mẹ bằng giọng say",
            "Kể một chuyện tình cảm bí mật trong 2 phút",
            "Đổi ghế ngồi với người bạn ít thân nhất tối nay",
            "Tự phạt 2 ly nếu không dám làm một việc cả nhóm yêu cầu",
            "Uống mà không được nhìn xuống ly",
        ],
    },
    {
        id: "toiben",
        level: "LV.3",
        name: "TỚI BẾN",
        icon: "▲",
        accent: "#0033FF",
        accentText: "#fff",
        btnBg: "#0033FF",
        btnText: "#fff",
        desc: "Không dành cho người yếu tim. Câu hỏi cực độ, thách thức điên rồ.",
        tag: "WILD",
        truth: [
            "Điều bạn chưa bao giờ kể cho ai trong nhóm này nghe?",
            "Ai là người bạn thích nhất trong nhóm này — và tại sao?",
            "Nói ra một bí mật có thể làm ai đó giận bạn tối nay",
            "Khoảnh khắc bạn xấu hổ nhất trong đời là gì?",
            "Ai trong nhóm bạn nghĩ sẽ ly hôn sớm nhất?",
            "Điều bạn không bao giờ dám nói thẳng với sếp là gì?",
            "Bạn đã từng phản bội bạn thân chưa? Kể chi tiết",
            "Điều bạn nói dối nhiều nhất với người thân là gì?",
            "Nếu phải chọn một người trong nhóm này để tranh thủ 24h — bạn chọn ai?",
            "Kể một bí mật mà nếu người liên quan nghe được, mọi thứ sẽ thay đổi",
        ],
        dare: [
            "Gửi một tin nhắn thật thà cho người bạn thầm thích",
            "Để mọi người trong nhóm post bất cứ ảnh gì lên story của bạn",
            "Gọi điện cho sếp và nói 'Mai tôi nghỉ'",
            "Để người bên cạnh đọc 10 tin nhắn gần nhất trong điện thoại",
            "Uống 3 ly liên tiếp không nghỉ",
            "Nói thật 3 điều bạn KHÔNG thích về người ngồi đối diện",
            "Để cả nhóm đặt nick name mới cho bạn trên điện thoại",
            "Nhắn tin cho người cuối cùng bạn nói chuyện: 'Anh/chị thích em không?'",
            "Kể chi tiết một cuộc cãi nhau tệ nhất bạn từng có",
            "Để cả nhóm đọc conversation dài nhất trên điện thoại",
        ],
    },
];

export const TICKER = [
    "UỐNG ĐI",
    "THẬT HAY THÁCH",
    "KHÔNG CÓ ĐƯỜNG LÙI",
    "AI DÁM?",
    "TỚI BẾN",
    "PHẠT UỐNG",
    "GAME ON",
    "UỐNG ĐI",
    "THẬT HAY THÁCH",
    "KHÔNG CÓ ĐƯỜNG LÙI",
    "AI DÁM?",
    "TỚI BẾN",
    "PHẠT UỐNG",
    "GAME ON",
];

export const PLAYER_COLORS = [
    "#FF3300",
    "#0033FF",
    "#FFE600",
    "#00C44F",
    "#FF69B4",
    "#FF8C00",
    "#9B59B6",
    "#1ABC9C",
];
